// Curriculum data for the Konstrukteurspult learning platform.
// Sourced from the "Themenübersicht Metallbaukonstrukteur/in Zusatzlehre gem. Ausbildungsprogramm".
window.TB_NAMES = {
  TB1: "Arbeitsorganisation & Grundlagen",
  TB2: "Sicherheit & Normen",
  TB3: "Mathematik & Physik",
  TB4: "Offener Bereich",
  TB5: "Bauphysik",
  TB6: "Skizzieren & Konstruktion",
  TB7: "Verbindungstechnik",
  TB8: "Statik & Festigkeitslehre",
  TB9: "Werkstoffe & Beton",
  TB10: "Oberfläche & Ökologie",
  TB11: "Kalkulation",
  TB12: "Beschläge & Wartung"
};

window.CURRICULUM = [
  { sem: 1, title: "Semester 1", topics: [
    { id: "s1-01", name: "Arbeitsabläufe", lekt: 5, tb: "TB1",
      explain: "Systematische Abfolge der Arbeitsschritte in Werkstatt und Montage – von Materialbereitstellung über Zuschnitt und Bearbeitung bis zur Übergabe. Ziel ist es, Wege, Wartezeiten und Fehlerquellen durch eine durchdachte Reihenfolge zu minimieren.",
      method: "Erstelle für 2–3 typische Aufträge dein eigenes Ablaufdiagramm (Post-its oder Flowchart) und vergleiche es mit dem tatsächlichen Vorgehen im Betrieb." },
    { id: "s1-02", name: "Unfallverhütung", lekt: 5, tb: "TB2",
      explain: "Grundsätze der Suva-Unfallverhütung im Metallbau: persönliche Schutzausrüstung, Absturzsicherung, sicherer Umgang mit Maschinen (Sägen, Schweissgeräte, Kran) sowie Verhalten bei Notfällen.",
      method: "Karteikarten mit „Gefahr → Schutzmassnahme“ erstellen und wöchentlich 5 Karten per Spaced Repetition abfragen." },
    { id: "s1-03", name: "Algebra", lekt: 33, tb: "TB3",
      explain: "Grundlage des technischen Rechnens: Termumformung, die vier Grundrechenarten mit Buchstabengrössen, Potenzen, Klammern, ganze Zahlen, Bruchrechnen und Gleichungen 1. Grades. Diese Regeln sind die Basis für Statik-, Kalkulations- und Bauphysikrechnungen.",
      formulas: "Grundrechenarten: a+b=b+a  ·  a·b=b·a\nPotenzen: aᵏ · aⁿ = aᵏ⁺ⁿ   aᵏ : aⁿ = aᵏ⁻ⁿ\nKlammern: +(a−b) = a−b     −(a−b) = −a+b\nGleichung lösen: Waage-Prinzip — was links passiert, muss rechts auch passieren.",
      method: "Täglich 10 Aufgaben aus dem Skript rechnen und sofort kontrollieren. Formelkarte für Potenz-, Klammer- und Gleichungsregeln griffbereit halten." },
    { id: "s1-04", name: "Physikalische Grundlagen", lekt: 22, tb: "TB3",
      explain: "Physikalische Grössen als Zahlenwert × Einheit: Kraft, Masse, Dichte, Arbeit, Leistung, elektrische Grundgrössen. Basis für reale Berechnungen wie Stahlgewicht, Hebelkräfte oder Widerstände in Anlagen.",
      formulas: "Dichte: ρ = m / V\nArbeit: W = F · s      Leistung: P = F · s / t\nHebelgesetz: Kraft × Hebelarm = Last × Hebelarm der Last\nOhm'sches Gesetz: U = I · R      Widerstand: R = ρ · l / A",
      method: "Formelsammlung mit Einheiten führen; zu jeder Formel eine konkrete Metallbau-Anwendung notieren, z.B. Gewicht eines Stahlträgers berechnen." },
    { id: "s1-05", name: "Sicherheitsvorschriften", lekt: 5, tb: "TB2",
      explain: "Betriebliche und gesetzliche Sicherheitsvorschriften (EKAS-Richtlinien, ArGV) für Werkstatt und Montage, insbesondere Gerüst-, Kran- und Hebezeugsicherheit.",
      method: "Jede Vorschrift in max. 3 eigenen Sätzen zusammenfassen und mit einem konkreten Baustellenbeispiel verknüpfen." },
    { id: "s1-06", name: "Trigonometrie", lekt: 20, tb: "TB3",
      explain: "Winkelberechnung im rechtwinkligen und allgemeinen Dreieck (Sinus, Cosinus, Tangens, Sinus- und Cosinussatz) – zentral für Schrägschnitte, Treppenwinkel, Geländer und Dachkonstruktionen.",
      formulas: "sin α = Gegenkathete / Hypotenuse\ncos α = Ankathete / Hypotenuse\ntan α = Gegenkathete / Ankathete\nSinussatz: a/sin α = b/sin β = c/sin γ",
      method: "Zu jeder Formel eine Skizze eines realen Metallbauteils (z.B. Treppenwinkel) zeichnen, dann erst rechnen." },
    { id: "s1-07", name: "Qualitätsmanagementsysteme", lekt: 5, tb: "TB1",
      explain: "Aufbau und Zweck von QM-Systemen (z.B. ISO 9001) im Betrieb: Prozessdokumentation, Prüfprotokolle, kontinuierliche Verbesserung nach dem PDCA-Zyklus.",
      method: "Den PDCA-Zyklus (Plan–Do–Check–Act) an einem eigenen Werkstattbeispiel durchdenken und schriftlich festhalten." },
    { id: "s1-08", name: "SIA-Normen", lekt: 5, tb: "TB2",
      explain: "Für den Metallbau relevante SIA-Normen (z.B. SIA 263 Stahlbau, SIA 261 Einwirkungen auf Tragwerke) regeln Bemessung, Ausführung und Verantwortlichkeiten.",
      method: "Übersichtstabelle führen: Normnummer → Thema → Relevanz für die eigene Praxis." },
    { id: "s1-09", name: "Bauphysik Wärme", lekt: 7, tb: "TB5",
      explain: "Wärmetransport durch Bauteile via Leitung, Konvektion und Strahlung. Metall leitet Wärme sehr gut, deshalb sind Wärmebrücken bei Fenstern und Fassaden ein zentrales Thema.",
      method: "Eine Schnittzeichnung eines Fensterprofils anfertigen und den Wärmefluss mit Pfeilen einzeichnen." },
    { id: "s1-10", name: "Bauphysik U-Wert", lekt: 6, tb: "TB5",
      explain: "Der U-Wert beschreibt den Wärmedurchgang eines Bauteils in W/(m²K) – je kleiner, desto besser die Dämmung.",
      formulas: "U = 1 / R_total\nR (pro Schicht) = d / λ   (d = Dicke, λ = Wärmeleitfähigkeit)",
      method: "Den U-Wert eines einfachen Beispielprofils selbst durchrechnen und mit MINERGIE-Grenzwerten vergleichen." },
    { id: "s1-11", name: "Skizzieren: Treppen, Geländer, Fenster, Türen", lekt: 30, tb: "TB6",
      explain: "Freihand- und Massstabskizzen von Standardbaugruppen: Wangentreppen und Stufenanschlüsse, Geländer (Pfosten, Handlauf, Füllstäbe), Fenster- und Türprofile inkl. Anschlussdetails.",
      method: "Täglich eine Baugruppe dreifach üben: Vorlage abzeichnen → aus dem Gedächtnis skizzieren → mit Bemassung beschriften." },
    { id: "s1-12", name: "Skizzieren: Gitter, Vordächer, Stahlbau", lekt: 19, tb: "TB6",
      explain: "Skizzieren von Gitterrostkonstruktionen, Vordachtragwerken (Konsolen, Wasserabläufe) und klassischen Stahlbauteilen wie Trägern, Stützen und Anschlüssen.",
      method: "Reale Bauteile fotografieren und als bemasste Skizze nachzeichnen (Foto-zu-Skizze-Übung)." }
  ]},
  { sem: 2, title: "Semester 2", topics: [
    { id: "s2-01", name: "Bauphysik U-Wert (Vertiefung)", lekt: 7, tb: "TB5",
      explain: "Vertiefung der U-Wert-Berechnung für zusammengesetzte Metall-Glas-Konstruktionen inkl. linearem Wärmebrückenverlust Ψ an Anschlussdetails.",
      method: "Eine komplette U-Wert-Berechnung eines Fassadenelements Schritt für Schritt rechnen und mit dem SIA-Grenzwert vergleichen." },
    { id: "s2-02", name: "Längen-, Winkel-, Flächen-, Körperberechnungen", lekt: 15, tb: "TB3",
      explain: "Umrechnen von Längen, Flächen und Hohlraum-/Volumenmassen zwischen den gebräuchlichen Einheiten – Grundlage für jede Massangabe im Werkplan.",
      formulas: "Längenmasse (Faktor 10 je Stufe): mm → cm → dm → m → …→ km\n1000 mm = 100 cm = 10 dm = 1 m ; 1000 m = 1 km\n\nFlächenmasse (Faktor 100 je Stufe): mm² → cm² → dm² → m² → a → ha → km²\n1 000 000 mm² = 10 000 cm² = 100 dm² = 1 m² ; 1 000 000 m² = 10 000 a = 100 ha = 1 km²\n\nHohlmasse (Faktor 10 je Stufe, 1 cm³ = 1 ml): ml → cl → dl → l(=dm³) → hl\n1000 ml = 100 cl = 10 dl = 1 l ; 100 l = 1 hl",
      method: "Für jede Grösse eine eigene „Umrechnungstreppe“ zeichnen und laminieren; täglich 5 Umrechnungen ohne Formelblatt rechnen, danach kontrollieren." },
    { id: "s2-03", name: "Schrauben, Nieten, Schweissen", lekt: 10, tb: "TB7",
      explain: "Verbindungstechniken im Metallbau: Schraubenverbindungen (Festigkeitsklassen, Anzugsdrehmomente), Nietverbindungen (Blind-/Vollniete) und Schweissverfahren (MIG/MAG, WIG, Elektrode) inkl. Nahtarten und Prüfung.",
      method: "Vergleichstabelle erstellen: Verbindungsart | Einsatzgebiet | Vor-/Nachteil | typische Norm." },
    { id: "s2-04", name: "Präsentation praktische Beispiele", lekt: 5, tb: "TB1",
      explain: "Aufbereitung und mündliche Präsentation eines eigenen Praxisbeispiels – vom selbst gefertigten Bauteil bis zur Montage – inkl. Herausforderungen und Lösungsweg.",
      method: "3-Satz-Struktur üben: Ausgangslage – Vorgehen – Ergebnis/Lernpunkt. Laut vor Kolleg:innen oder Spiegel vortragen." },
    { id: "s2-05", name: "Bauphysik Feuchtigkeit", lekt: 10, tb: "TB5",
      explain: "Feuchteschutz bei Metallkonstruktionen: Tauwasserbildung, Diffusion und Kondensat an kalten Metallteilen – zentrales Korrosionsrisiko an Wärmebrücken.",
      method: "Ein Glaser-Diagramm einmal komplett von Hand durchrechnen, um die Kondensationsebene zu verstehen." },
    { id: "s2-06", name: "Statische Systeme", lekt: 10, tb: "TB8",
      explain: "Grundlegende statische Systeme: Einfeldträger, Kragarm, Durchlaufträger, Fachwerk. Bestimmung von Lagerarten (fest, los, eingespannt) und Freiheitsgraden.",
      method: "Für jedes System zuerst ein Freikörperbild zeichnen und die Lagerreaktionen benennen – erst danach rechnen." },
    { id: "s2-07", name: "Auflager, Querkraft, Moment", lekt: 7, tb: "TB8",
      explain: "Berechnung der Auflagerreaktionen aus den Gleichgewichtsbedingungen (ΣF = 0, ΣM = 0) und daraus Ableitung von Querkraft- und Momentenverlauf entlang des Trägers.",
      formulas: "ΣFvertikal = 0     ΣFhorizontal = 0     ΣM(Drehpunkt) = 0",
      method: "Festes 4-Schritt-Schema üben: 1) Freikörperbild 2) Gleichgewicht aufstellen 3) Auflagerkräfte lösen 4) Q- und M-Linie zeichnen." },
    { id: "s2-08", name: "Werkstoffprüfungen / Zulassungen", lekt: 5, tb: "TB9",
      explain: "Prüfverfahren für Metallwerkstoffe (Zugversuch, Härteprüfung, Kerbschlagbiegeversuch) und Zulassungsnachweise wie CE-Kennzeichnung und Werkszeugnisse.",
      method: "Pro Prüftyp eine Karteikarte: Was wird geprüft? Welche Kennwerte liefert er? (z.B. Zugversuch → Streckgrenze, Zugfestigkeit)." },
    { id: "s2-09", name: "Festigkeitslehre", lekt: 30, tb: "TB8",
      explain: "Spannungen (Zug, Druck, Biegung, Schub) und Verformungen in Bauteilen; Nachweis der Beanspruchung gegen Fliess- und Bruchgrenze.",
      formulas: "Normalspannung: σ = F / A\nBiegespannung: σb = M / W\nNachweis: σvorhanden ≤ σzulässig",
      method: "Aufgaben immer in fester Reihenfolge lösen: Querschnittswerte bestimmen → Beanspruchung berechnen → mit zulässiger Spannung vergleichen. Formeln inkl. Einheiten auf Karteikarten." },
    { id: "s2-10", name: "Architektenpläne", lekt: 4, tb: "TB1",
      explain: "Lesen und Interpretieren von Architektenplänen: Grundriss, Schnitt, Ansicht, Massstäbe und Planköpfe als Grundlage der Metallbau-Werkplanung.",
      method: "Einen echten Plan Zeile für Zeile „übersetzen“: Was bedeutet jedes Symbol, jede Massangabe für den Metallbau konkret?" },
    { id: "s2-11", name: "Skizzieren: Fenster, Türen", lekt: 44, tb: "TB6",
      explain: "Vertiefte Skizzierpraxis für Fenster- und Türkonstruktionen inkl. Beschlaganschluss, Dichtungsebenen und Fassadenanschluss.",
      method: "Von einfach zu komplex steigern: pro Woche 3 neue Anschlussdetails skizzieren und vollständig beschriften." },
    { id: "s2-12", name: "Skizzieren: Vordächer, Stahlbau", lekt: 15, tb: "TB6",
      explain: "Skizzieren von Vordachtragwerken und stahlbaulichen Standarddetails wie Stützenfuss, Trägeranschluss und Verband.",
      method: "Bestehende Werkpläne aus dem Betrieb als Vorlage nehmen und in eigener Handschrift neu skizzieren." }
  ]},
  { sem: 3, title: "Semester 3", topics: [
    { id: "s3-01", name: "Oberflächenbehandlungen", lekt: 15, tb: "TB10",
      explain: "Verfahren zum Oberflächenschutz von Metall: Feuerverzinken, galvanisches Verzinken, Pulverbeschichtung, Eloxieren von Aluminium und Anstriche inkl. Vor- und Nachbehandlung.",
      method: "Vergleichstabelle mit Musterplatten führen: Verfahren | Schichtdicke | Einsatzbereich | Kosten/Aufwand." },
    { id: "s3-02", name: "Korrosionseinflüsse", lekt: 5, tb: "TB10",
      explain: "Korrosionsarten wie elektrochemische Korrosion, Kontaktkorrosion zwischen unterschiedlichen Metallen und Lochkorrosion – abhängig von Feuchte, Salz und Luftschadstoffen.",
      method: "Eigene Merkliste „Wann rostet was mit was?“ nach der galvanischen Reihe erstellen und im Alltag anwenden." },
    { id: "s3-03", name: "Kalkulation 1", lekt: 15, tb: "TB11",
      explain: "Grundlagen der Angebotskalkulation: Material-, Lohn- und Maschinenkosten, Zuschläge für Gemeinkosten, Gewinn und Risiko, Aufbau einer einfachen Offertkalkulation.",
      method: "Eine reale Materialliste nehmen und komplett von Hand durchkalkulieren." },
    { id: "s3-04", name: "Auflager, Querkraft, Moment (Vertiefung)", lekt: 18, tb: "TB8",
      explain: "Vertiefung: Auflager-, Querkraft- und Momentenberechnung bei mehrfeldrigen Systemen und kombinierten Lastfällen.",
      method: "Dasselbe 4-Schritt-Schema aus Semester 2 anwenden, aber mit mehreren gleichzeitig wirkenden Lasten üben." },
    { id: "s3-05", name: "Beton", lekt: 5, tb: "TB9",
      explain: "Beton als Verbundwerkstoff für Fundamente und Befestigungen von Metallkonstruktionen: Betongüten, Bewehrung, chemische und mechanische Verankerungstechnik.",
      method: "Dübeltabellen eines Herstellers durchgehen und Tragfähigkeiten an eigenen Beispielen nachvollziehen." },
    { id: "s3-06", name: "Kalkulation 2", lekt: 15, tb: "TB11",
      explain: "Vertiefte Kalkulation: Nachkalkulation, Soll-Ist-Vergleich, Abrechnung bei Regie- und Pauschalaufträgen sowie Umgang mit Nachträgen.",
      method: "Eine abgeschlossene Baustelle aus dem eigenen Betrieb nachkalkulieren und mit der ursprünglichen Offerte vergleichen." },
    { id: "s3-07", name: "Beschläge", lekt: 5, tb: "TB12",
      explain: "Beschlagstechnik für Fenster, Türen und Tore: Bänder, Schlösser, Schliessbleche, Dichtungen und Automatiktüren – Auswahl nach Einsatzbereich.",
      method: "Beschlagskatalog-Übung: zu 5 Bauteilen den passenden Beschlag auswählen und die Wahl begründen." },
    { id: "s3-08", name: "Dimensionierung", lekt: 20, tb: "TB8",
      explain: "Bemessung von Bauteilquerschnitten (Profile, Bleche) anhand von Lastannahmen und Nachweisen nach SIA 263 – Auswahl des kleinsten ausreichenden Profils.",
      method: "Für ein Standardbauteil drei Profilvarianten durchrechnen und die wirtschaftlichste begründet auswählen." },
    { id: "s3-09", name: "Bauphysik Akustik", lekt: 11, tb: "TB5",
      explain: "Schallschutz bei Metallkonstruktionen: Luft- und Körperschall, Schalldämmmass und die Entkopplung von Metallteilen zur Vermeidung von Schallbrücken.",
      method: "Ein eigenes Bauteil (z.B. Fensterrahmen) auf mögliche Schallbrücken untersuchen und Gegenmassnahmen skizzieren." },
    { id: "s3-10", name: "Ökologie", lekt: 8, tb: "TB10",
      explain: "Ökologische Aspekte im Metallbau: Recyclingfähigkeit von Stahl und Aluminium, graue Energie, nachhaltige Oberflächenbehandlung und Lebenszyklusbetrachtung.",
      method: "Graue-Energie-Vergleich zweier Materialvarianten (z.B. Stahl vs. Aluminium) für ein Bauteil recherchieren und gegenüberstellen." },
    { id: "s3-11", name: "Skizzieren: Fassadenbau, Lichtdächer, Schaufenster", lekt: 23, tb: "TB6",
      explain: "Skizzieren komplexer Glasfassaden-, Lichtdach- und Schaufensterkonstruktionen inkl. Statik- und Dichtungsdetails.",
      method: "Fassadendetails aus Fachzeitschriften oder Katalogen nachskizzieren, danach eine eigene Variante entwerfen." },
    { id: "s3-12", name: "Skizzieren: Tore, Vordächer, Stahlbau", lekt: 20, tb: "TB6",
      explain: "Skizzieren von Torkonstruktionen (Schiebe-, Sektional-, Falttore), Vordächern und weiteren Stahlbaudetails.",
      method: "Funktionsprinzip jedes Tortyps zuerst in eigenen Worten erklären, dann erst skizzieren – Verständnis vor Darstellung." }
  ]},
  { sem: 4, title: "Semester 4", topics: [
    { id: "s4-01", name: "Arbeitsabläufe: Materiallieferung bis Montage", lekt: 5, tb: "TB1",
      explain: "Gesamtprozess eines Projekts: Materialdisposition, Lieferung, Zwischenlagerung, Vorfertigung, Transport und Montage vor Ort inkl. Schnittstellen zu anderen Gewerken.",
      method: "Prozesslandkarte des letzten eigenen Projekts zeichnen und Engpässe markieren." },
    { id: "s4-02", name: "Anforderungen aus Normen", lekt: 5, tb: "TB2",
      explain: "Zusammenführung der wichtigsten normativen Anforderungen (SIA, EN, Suva) für die praktische Bauausführung im Metallbau.",
      method: "Ein eigenes Normen-Merkblatt „Was gilt wann?“ als Referenzkarte für die Baustelle erstellen." },
    { id: "s4-03", name: "Bauschäden", lekt: 10, tb: "TB2",
      explain: "Typische Bauschäden an Metallkonstruktionen: Korrosionsschäden, Wärmebrückenschäden, Ausführungsfehler bei Anschlüssen und mangelhafte Entwässerung.",
      method: "Schadensfälle aus dem eigenen Betrieb sammeln und die Ursache-Wirkung-Kette mit der 5-Why-Methode analysieren." },
    { id: "s4-04", name: "Vordimensionierung", lekt: 30, tb: "TB8",
      explain: "Schnelle, überschlägige Bemessung von Bauteilen in der frühen Projektphase mit Faustformeln/Tabellenwerken, bevor die genaue Bemessung erfolgt.",
      method: "Faustformel-Kärtchen für häufige Bauteile (Träger, Stütze, Geländerpfosten) erstellen und später mit der genauen Berechnung verifizieren." },
    { id: "s4-05", name: "Montagekonzept", lekt: 10, tb: "TB6",
      explain: "Planung der Montagereihenfolge, Hebe- und Befestigungstechnik, Baustellenlogistik und Sicherung während der Montage von Metallbauteilen.",
      method: "Für ein Bauteil ein Montagekonzept in 5 Schritten aufschreiben: Vorbereitung, Transport, Heben, Befestigen, Sichern/Kontrolle." },
    { id: "s4-06", name: "Wartung und Pflege", lekt: 10, tb: "TB12",
      explain: "Wartungspläne für Metallbauteile wie Türen, Tore und Fassaden: Schmierung von Beschlägen, Kontrolle von Dichtungen, Nachbehandlung von Oberflächen, Serviceintervalle.",
      method: "Eine Wartungscheckliste für ein reales Bauteil erstellen: Was? Wie oft? Womit?" },
    { id: "s4-07", name: "Offener Bereich · Vertiefung", lekt: 21, tb: "TB4",
      explain: "Freier Themenbereich für individuelle Vertiefung – eigene Praxisthemen, Wiederholung schwacher Bereiche oder betriebsspezifische Inhalte.",
      method: "Wähle dein schwächstes Thema aus einem anderen Semester aus und vertiefe es gezielt in diesem Slot." },
    { id: "s4-08", name: "Offener Bereich · Prüfungstraining", lekt: 21, tb: "TB4",
      explain: "Zweiter freier Themenbereich – ideal zur gezielten Prüfungsvorbereitung über alle bisherigen Semester hinweg.",
      method: "Alte Prüfungen unter Zeitdruck simulieren, danach jeden Fehler einzeln analysieren und dem passenden Thema zuordnen." },
    { id: "s4-09", name: "Skizzieren: Fassadenbau, Lichtdächer, Schaufenster (Vertiefung)", lekt: 28, tb: "TB6",
      explain: "Vertiefte Praxis komplexer Fassaden-, Lichtdach- und Schaufensterdetails mit Fokus auf Ausführungsreife auf Werkplanniveau.",
      method: "Eine vollständige Werkplan-Skizze eines Fassadenausschnitts inkl. Bemassung und Beschriftung anfertigen." },
    { id: "s4-10", name: "Skizzieren: Tore, Vordächer, Stahlbau (Vertiefung)", lekt: 20, tb: "TB6",
      explain: "Abschliessende Vertiefung der Tor-, Vordach- und Stahlbauskizzen auf Prüfungsniveau.",
      method: "Unter Zeitdruck wie in der Prüfung eine Skizze in max. 20 Minuten anfertigen und die eigene Qualität danach selbst bewerten." }
  ]}
];
